version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
volumes:
  redis-volume:
